### PR TITLE
 Write a Python program to get the length in bytes of one array item…

### PR DESCRIPTION
**Pull request by SiddhanGaur**
… in the internal representation

### CODE REVIEW

**Comment by tejas-trivedi** [comment]
You file ```Time Delta_HackerRank.py``` is empty

**Comment by tejas-trivedi** [comment]
Your file Time Delta_HackerRank.py is empty

**Comment by SiddhanGaur** [comment]
I must have forgot to save first. Can i re-upload it ?

**Comment by tejas-trivedi** [comment]
Why have you deleted your entire directory?

**Comment by SiddhanGaur** [comment]
sir, it was not showing all  commits that i uploaded and when i was using push command to add new files it was showing error. So I thought i would delete this one and add another folder.

**Pull request closed without merging**
