### PR TITLE
Sarthak's Problem

### PR DESCRIPTION
**Pull request by vanya31**

### CODE REVIEW

**Comment by tejas-trivedi** [comment]
Incorrect Solution! The pattern your code prints is completely different from what was shared in the group.

**Comment by tejas-trivedi** [comment]
Python code is still not correct. The lower half prints some arbitrary pattern. 
Try again.. let me know if you face any issues.

**Comment by vanya31** [comment]
> Python code is still not correct. The lower half prints some arbitrary pattern.
> Try again.. let me know if you face any issues.

Yessiir I mentioned in the readme I was not able to solve the downward pyramid in python..not getting how to decrement the value..so instead I wrote the quote in cpp

**Comment by tejas-trivedi** [comment]
Alright, then remove the .py file and commit again along with todays' code.

**Pull request merged**
